### ISSUE TITLE
 Campaign: Save/cache doors, posters and flyers when offline

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene_app#182]
**As an app user, I need to be able to enter campaign objects (doors, posters, flyers) when offline and have these be uploaded to the server when a connection is reestablished in order to manage campaign data even without an internet connection.**

Acceptance criteria:
- [ ] Data should be automatically synchronized when an internet connection is established
- [ ] Data persist, even when the app is closed
- [ ] Option for photos to be uploaded only with an active WiFi connection

**Comment by nscharioth** [comment]
Not mentioned in 'Lastenheft'

**Comment by JuliaFreitagBGSt** [comment]
Funktion(en) nice to have, aber weder im Lastenheft genannt noch easy umsetzbar. Daher closed as not planned. Wir verknüpfen diesen Need mit #172 und #177 und machen uns Gedanken dazu, wie User*innen ohne Internet die App nutzen können.
