### ISSUE TITLE
Campaign: Homepage Posters

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene_app#183]
**As an app user, I want to see all posters displayed on a map in oder to enter the location for a newly hung poster, to be able to repair/replace a damaged poster, or to remove a poster entirely (e.g. after an election has ended).**

The main map for the user to look at or manage posters. Hung posters, posters that need to be replaced and posters that have already been taken down are coordinated in an easily understandable map.

Registered poster locations are shown as icons on the map. Areas and Polling Stations [_Wahllokale_] entered into the separate campaign planning tool (until October 2024: _Wahlatlas_ / as of October 2024: in parallel development by Pollion) can be displayed and hidden using a filter.
Posters can be added through a click on the central add-POI element (address is entered analog to the Doors functionality and, optionally, with name and photo).
Poster icons are green (active), red (damaged), or gray (marked as taken down). Tapping on a poster icon shows the commensurate picture in an overlay, a tap on the overlay allows the user to edit (address inputs) and show / edit / remove the picture in full size. Furthermore, the poster can be set as damaged or taken down through toggles, as well as commented in a free text field.
Where needed, posters can be removed completely from the map. The button "_Eintrag löschen_" triggers the feedback: "_Möchtest du das Plakat wirklich - endgültig - löschen? Markiere abgehängte Plakate bitte als abgehängt, statt sie zu löschen!_" In the overlay "_Meine Plakate_", users can see a list of posters they have registered, which are sorted by date of entry. These posters can also be edited and deleted from this overlay.

Acceptance criteria:
- [x] #185 
- [x] #267 
- [ ] #216
- [ ] #279
- [ ] On the map, users can identify damaged poster locations (red dot)
- [ ] On the map, users can identify poster locations (green dot)
- [ ] On the map, users can identify poster locations that have been taken down (grey dot)
- [ ] #173 
- [ ] #197 
- [ ] #263 
- [ ] #269 
- [ ] #285 
- [ ] #286 
- [ ] #287 
- [ ] #288 
- [ ] #289 
- [ ] #290 

Design:
<img width="316" alt="361200427-10d2c435-f6fa-4ead-9460-3e34d47e7b60" src="https://github.com/user-attachments/assets/0dc6f3a9-b7bb-4246-9b97-acfaa95c0a7e">
Prototype:
https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2670-9551&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

API endpoint reference: https://github.com/verdigado/gruene-api/issues/61

Pollion reference: https://github.com/pollion/sunflower-app/issues/25

**Comment by nscharioth** [comment]
Pollion reference: https://github.com/pollion/sunflower-app/issues/25

**Comment by nscharioth** [comment]
Please review issue description and place in "Ready for Development" column. @leagerndt @JuliaFreitagBGSt
