### ISSUE TITLE
Campaign | Posters: Tool Tip

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene_app#184]
As an app user, I would like to see concise details of a poster in order to quickly access photo(s) of its location and important information (e.g. its current condition).

- [ ] Users can see the poster photo in the tool tip
- [ ] Users can zoom the photo as desired

**Comment by nscharioth** [comment]
Functionality not mentioned in 'Lastenheft'

**Comment by JuliaFreitagBGSt** [comment]
User Story veraltet. Die Bedarfe haben sich geändert und gewünschte Funktionen gehen in anderen Issues auf (u.a. #197 oder #264 )
