### ISSUE TITLE
Functional Requirements: Login Screen

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene_app#201]
In einem Anmeldungs- und Introscreen können sich Nutzer:innen "Jetzt einloggen", oder die "App erkunden". Außerdem werden auf dem Anmeldungs- und Introscreen die Links zu Datenschutz und Impressum eingeblendet.

Die Seite enthält auch einen "Unterstützen" Button, mit welchem Nutzer:innen (in einem Browsertab) auf die Spendenseite geleitet werden, und einen Button zum "Gast-Login mit Einladungscode".

**Comment by steffenkleinle** [comment]
@iantrieschmann @JuliaFreitagBGSt could you please provide the correct URL to the donation page? Thanks
