### ISSUE TITLE
Functional Requirements: App-Login via Keycloak for Party Members

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene_app#202]
**As a member, I want to be able to log in to the app with my "_Grünes Netz_" account information in order to obtain and maintain secure access to the data in the app and also be identified and authenticated using this information.**

From the start screen, users can access the login through a click on the button "_Jetzt einloggen_". The login process as well as the forgot password flow run through the Keycloak service. The login design is adapted to the prototype, to existing Keycloak design and generally to the most current _Grundlagendesign_.

**Comment by steffenkleinle** [comment]
Perhaps there is something reusable in this branch: https://github.com/verdigado/gruene_app/compare/legacy...86-55-keycloak-authenticator-implementierung

**Comment by JuliaFreitagBGSt** [comment]
issue is reviewed
