### ISSUE TITLE
Functional Requirements: Top Bar

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene_app#206]
**The top bar always includes the title of the current page to make clear where users currently are in the app.** Additionally, there is always a button here that leads to the app settings (except, of course, on the settings page itself). In lower levels of the page hierarchy, there can be a back button where meaningful. On pages with fold-out filter funtions, users can find a button to access the filter. On the campaign pages, the contents there can be refreshed / synchronized via a button in the top bar. The respective status of the top bar per area can be found in the design prototype.

Design:

![grafik](https://github.com/user-attachments/assets/8c08894e-a891-432e-ba1d-3f2dfaa35c25)

![grafik](https://github.com/user-attachments/assets/ca42f01e-eabb-4c54-aa8c-d8b375a36d25)

![grafik](https://github.com/user-attachments/assets/a4119c04-9b74-4bb6-972e-68df898f495c)

![grafik](https://github.com/user-attachments/assets/1f9725eb-43cf-4f17-a2b7-3dfd9559e9c9)

![grafik](https://github.com/user-attachments/assets/65d4d6f3-9330-4001-8a18-6223f04c22f1)

**Comment by JuliaFreitagBGSt** [comment]
instead of News the title should be "Aktuelles"
