### ISSUE TITLE
Functional Requirements: Intro Screen

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene_app#209]
When the app is opened for the first time, a small slideshow on the app's functions can be run through.

In a login and intro screen, users can “Log in now” or “Explore the app”. After going through up to 5 slides, users are equally taken to the login screen. In addition, links to the privacy policy and imprint are displayed on the login and intro screen.

The page also contains a “Support” button, which redirects users (in a browser tab) to the donation page, and a button for “Guest login with invitation code”.

Tasks:
- #102 

![grafik](https://github.com/user-attachments/assets/462ea787-3e76-46bd-b33a-8250a0eb6841)
![grafik](https://github.com/user-attachments/assets/c93138c6-be50-46a3-808d-208683fae2b4)
![grafik](https://github.com/user-attachments/assets/c676f94a-a601-4e1b-8a7d-a84fb5ab4e5b)

**Comment by JuliaFreitagBGSt** [comment]
@maxpfe please clarify why this issue is critical

**Comment by maxpfe** [comment]
@JuliaFreitagBGSt this is the only defined way to reach the login button. The only part, that can be delayed is the 'app-tour' which is already included in the 'release 2' package

**Comment by JuliaFreitagBGSt** [comment]
> @JuliaFreitagBGSt this is the only defined way to reach the login button. The only part, that can be delayed is the 'app-tour' which is already included in the 'release 2' package

Issue is reviewed. Login is ready for development, "app-tour" is postponed to release 2 @maxpfe @leagerndt

**Comment by steffenkleinle** [comment]
Duplicates #321.
