### ISSUE TITLE
Settings: Legal Texts/Disclaimers

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene_app#223]
**Users must be able to find and read information regarding editorial responsibility, data protection and the app's terms of use.**

Three pages are contained under the section "Rechtliches" in the main Settings page:

- #166 
- #165 
- #167 

Design:

![grafik](https://github.com/user-attachments/assets/b1fda63c-8a97-47bb-8c0c-f371756f8307)

Prototype: https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2487-12430&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

**Comment by maxpfe** [comment]
All three texts will be displayed from the website via 'in-app-browser'

**Comment by steffenkleinle** [comment]
For clarification: Should the bottom navigation bar also be visible in the settings screen as shown in the [screenshot](https://private-user-images.githubusercontent.com/157034929/375694223-b1fda63c-8a97-47bb-8c0c-f371756f8307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDkzNzMsIm5iZiI6MTczMDgwOTA3MywicGF0aCI6Ii8xNTcwMzQ5MjkvMzc1Njk0MjIzLWIxZmRhNjNjLThhOTctNDdiYi04YzBjLWYzNzE3NTZmODMwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMjE3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTAwNzMzN2NkYzE5ZDdmNzk2YzFiMTQyODhkNTVkMTFmNTllYTQxMDE0MTBjZWNhZDliYjcyZDNjYmJlMDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nN7WtAubRt3lrMWF9iCQiZ69ULD2NugQO6ZCQf9zDYk) in theissue description, even though the settings are not really part of the bottom navigation bar? If yes, should `Tools` be highlighted as shown in the screenshot?

My personal feeling would to not show the bottom navigation bar for screens that can't be opened (indirectly) through it.

**Comment by steffenkleinle** [comment]
@iantrieschmann @maxpfe @JuliaFreitagBGSt is it already clear what should happen/should be showed when clicking on `Impressum`/`Datenschutzerklärung`/`Nutzungsbedingungen`? In the figma prototype it is shown directly in the app but then also URLs and inappbrowser were mentioned. Please add the corresponding information to the three separate issues:
- #166 
- #165 
- #167

**Comment by JuliaFreitagBGSt** [comment]
> @iantrieschmann @maxpfe @JuliaFreitagBGSt is it already clear what should happen/should be showed when clicking on `Impressum`/`Datenschutzerklärung`/`Nutzungsbedingungen`? In the figma prototype it is shown directly in the app but then also URLs and inappbrowser were mentioned. Please add the corresponding information to the three separate issues:
> 
>     * [Impressum / Legal Notice #166](https://github.com/verdigado/gruene_app/issues/166)
> 
>     * [Datenschutzerklärung / Data Protection Statement #165](https://github.com/verdigado/gruene_app/issues/165)
> 
>     * [Nutzungsbedingungen / Terms of Use #167](https://github.com/verdigado/gruene_app/issues/167)

Yes, @maxpfe already stated that in a comment above. All three texts will be displayed from the website via 'in-app-browser'.

**Comment by steffenkleinle** [comment]
> > @iantrieschmann @maxpfe @JuliaFreitagBGSt is it already clear what should happen/should be showed when clicking on `Impressum`/`Datenschutzerklärung`/`Nutzungsbedingungen`? In the figma prototype it is shown directly in the app but then also URLs and inappbrowser were mentioned. Please add the corresponding information to the three separate issues:
> > ```
> > * [Impressum / Legal Notice #166](https://github.com/verdigado/gruene_app/issues/166)
> > 
> > * [Datenschutzerklärung / Data Protection Statement #165](https://github.com/verdigado/gruene_app/issues/165)
> > 
> > * [Nutzungsbedingungen / Terms of Use #167](https://github.com/verdigado/gruene_app/issues/167)
> > ```
> 
> Yes, @maxpfe already stated that in a comment above. All three texts will be displayed from the website via 'in-app-browser'.

Thanks for the reply. Are the URLs decided on yet?

**Comment by JuliaFreitagBGSt** [comment]
> > > @iantrieschmann @maxpfe @JuliaFreitagBGSt is it already clear what should happen/should be showed when clicking on `Impressum`/`Datenschutzerklärung`/`Nutzungsbedingungen`? In the figma prototype it is shown directly in the app but then also URLs and inappbrowser were mentioned. Please add the corresponding information to the three separate issues:
> > > ```
> > > * [Impressum / Legal Notice #166](https://github.com/verdigado/gruene_app/issues/166)
> > > 
> > > * [Datenschutzerklärung / Data Protection Statement #165](https://github.com/verdigado/gruene_app/issues/165)
> > > 
> > > * [Nutzungsbedingungen / Terms of Use #167](https://github.com/verdigado/gruene_app/issues/167)
> > > ```
> > 
> > 
> > Yes, @maxpfe already stated that in a comment above. All three texts will be displayed from the website via 'in-app-browser'.
> 
> Thanks for the reply. Are the URLs decided on yet?

For Impressum und Dateschutz, the URL is adressed in the respective issue. We do not yet have a URL for Nutzungsbedinungen. Please use a placeholder (f.e. Datenschutz)
