### ISSUE TITLE
Technological Requirements

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene_app#242]
Die App wird für Android und iOS entwickelt, um eine breite Zugänglichkeit zu gewährleisten. Es wird darauf geachtet, dass die App auch auf älteren Versionen dieser Plattformen funktioniert, sodass nicht nur die neuesten Geräte unterstützt werden müssen. Dies stellt sicher, dass auch Mitglieder mit älterer Hardware die App nutzen können, ohne zusätzliche Investitionen in neue Technologie tätigen zu müssen. Die Software wird bei neuen Versionen in App Store, Google Play Store & Github Releases deployed. Als Beta-Tester:in möchte ich jederzeit die aktuellste Version des develop Branch als Beta Release finden können, um zu den aktuellsten Entwicklungen Feedback geben zu können.

**Comment by nscharioth** [comment]
Not a developer task, therefore closed for similar reasons like #243, see comment: https://github.com/verdigado/gruene_app/issues/243#issuecomment-2466516648

If reopened please describe exact acceptance criteria for developers.
