### ISSUE TITLE
Basic Navigation and Project Folder Structure

### ISSUE THREAD

**Issue by NikoHadouken** [verdigado/gruene_app#249]
- [x] add bottom toolbar with navigation (just a simple, functional implementation of the Figma click dummy version)
- [x] create one empty view for every feature
- [ ] add project folder structure

Features and their name in code
* Artikel: news
* Wahlkampf: campaigns
* Mitglieder: profiles
* 2FA: mfa (because language constraints often forbid identifiers to start with a number)
* Apps: apps

**Comment by JuliaFreitagBGSt** [comment]
Issue is reviewed @maxpfe @leagerndt
