### ISSUE TITLE
Setup slang for i18n/l10n

### ISSUE THREAD

**Issue by steffenkleinle** [verdigado/gruene_app#252]
Available languages should be German (`de`) and English (`en`).
TBD: What should be the default if a different system language is used?

See https://pub.dev/packages/slang.

**Comment by volkramweber** [comment]
As far as i remember from our last meeting, there is no need for multiple languages so far?

**Comment by steffenkleinle** [comment]
> As far as i remember from our last meeting, there is no need for multiple languages so far?

Agreed. However, I think setting this up now is sooooo much easier then later so I'd just do that now. Even though I added an English translation file as example/for testing, I'd not keep the file up-to-date or even delete it again before merging the PR.

> multiple language availability should be part of the setup, for the first releases German is the only offered language and should be default for all system languages

Sounds good. I think translations should also not be done by us (not even to English) in any case.
