### ISSUE TITLE
Campaign | Posters: Submenu

### ISSUE THREAD

**Issue by nscharioth** [verdigado/gruene_app#267]
As an app user, I want a submenu for posters with the following options. 

Acceptance criteria:
- [x] 1st position: "Routen" (no link in Release 0*) 
- [x] 2nd position: "Wahllokale" (no link in Release 0*)  

An updated version is found in #340 

Further info for later releases:
- the menu options can be toggled on or off and is initially off.
- #271 
- #220 

<img width="312" alt="Bildschirmfoto 2024-11-03 um 13 51 54" src="https://github.com/user-attachments/assets/57e166d3-af4a-406d-ac4f-d12b87c4ffc5">
<img width="303" alt="Bildschirmfoto 2024-11-03 um 20 24 04" src="https://github.com/user-attachments/assets/b8034ee1-bc46-4016-9113-649b46d51cd8">

Prototype: https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2683-13221&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

Pollion reference: https://github.com/pollion/sunflower-app/issues/132

**Comment by nscharioth** [comment]
@leagerndt @JuliaFreitagBGSt 
Please review issue description and place in "Ready for Development" if ok.

**Comment by iantrieschmann** [comment]
Concept requires further refinement (see related discussion in #274). Due to this and the priority of other features for the federal elections in 2025, polling stations are to be parked in the backlog until further notice / capacities become available.
@nscharioth fyi

**Comment by nscharioth** [comment]
Updated to reflect Release 0*

**Comment by iantrieschmann** [comment]
Issue is reviewed, rfd

**Comment by Stift** [comment]
Last information was from yesterday, that there should be a THIRD option "experience areas". Could you please update the description to reflect this?
![image](https://github.com/user-attachments/assets/6f0b156f-b381-48f0-8c1b-31fb531aaecc)
