### ISSUE TITLE
Campaign | Doors: Submenu

### ISSUE THREAD

**Issue by nscharioth** [verdigado/gruene_app#268]
Clicking on doors in the menu bar #185 opens up a submenu for doors. The submenu has three options.

Acceptance criteria:
- [x] 1st position: "Besuchte Gebiete" (no link)
- [x] 2nd position: "Routen (no link)
- [x] 3rd position: "Fokusgebiete" links to #169
- [x] menu option "Fokusgebiete" toggled OFF initially
- [x] the menu options can be toggled on or off 

Note: Updated in #338.

Further information for later releases:
- #272 
- menu option "Besuchte Gebiete" toggled ON initially
- #170
- menu options "Fokusgebiete" and "Routen" toggled OFF initially

<img width="324" alt="Bildschirmfoto 2024-11-03 um 13 51 45" src="https://github.com/user-attachments/assets/3a3ad805-b5c4-4672-93b1-178d95263d51">
<img width="302" alt="Bildschirmfoto 2024-11-03 um 20 28 42" src="https://github.com/user-attachments/assets/c7a9d37d-bb09-4c95-babe-33063ccdce6f">

Prototype: https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2685-14248&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

Pollion reference: https://github.com/pollion/sunflower-app/issues/128

**Comment by nscharioth** [comment]
@leagerndt @JuliaFreitagBGSt 
Please review issue description and move to "Ready for Development" if ok.

**Comment by leagerndt** [comment]
"The menu options can be toggle on or off and is initially off." Which toggle are you mentioning here @nscharioth?

**Comment by nscharioth** [comment]
I mean the words in the submenu "Fokusgebiete", "Routen", "Bereiche". They are all initially OFF (not highlighted) and thus the map does not show these initially.

**Comment by nscharioth** [comment]
Based on https://github.com/verdigado/gruene_app/issues/272#issuecomment-2460254947 I have edited the main description above to reflect:

- [ ] menu option "Bereiche" renamed as "Besuchte Gebiete" and moved to left-most position
- [ ] the menu options can be toggle on or off 
- [ ] menu option "Besuchte Gebiete" toggled ON initially
- [ ] menu options "Fokusgebiete" and "Routen" toggled OFF initially

**Comment by JuliaFreitagBGSt** [comment]
order of submenu: Besuchte Gebiete - Routen - Fokusgebiete - Erfahrungsgebiete

**Comment by nscharioth** [comment]
Updated to reflect Release 0*
