### ISSUE TITLE
Introscreen

### ISSUE THREAD

**Issue by maxpfe** [verdigado/gruene_app#321]
After Splashscreen the user will see an introscreen with the following buttons: 'Jetzt einloggen' and 'App erkunden' -> App erkunden is no clickable in first release. Login leads to keycloak-login

**Comment by maxpfe** [comment]
'unterstützen' button and 'login- für nichtmiglieder' not part of release 1

**Comment by JuliaFreitagBGSt** [comment]
@leagerndt if new screenshots are necessary, pls provide and check user-flow

**Comment by steffenkleinle** [comment]
Closing, duplicate of #209.
